development:
  adapter: postgresql
  encoding: unicode
  database: guniv_development
  pool: 5
  username: rslixet
  password:	

test:
  adapter: postgresql
  encoding: unicode
  database: guniv_test
  pool: 5
  username: rslixet
  password: